### ISSUE TITLE
create a release number and tag when `npm run deploy`

### ISSUE THREAD

**Issue by vimark1** [vimark1/typist#15]
`npm run deploy`  should:

-  publish the app to the gh-pages branch 
- create a new tag for the release
- add tag somewhere in the app to say `v0.0.1`

**Comment by JoshDev1205** [comment]
Do it! in [here](https://github.com/vimark1/typist/pull/21)

**Comment by vimark1** [comment]
we're not using github pages for hosting anymore, will need to rethink this
