### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by smkamranqadri** [vimark1/typist#31]
We need to make it desktop app too, for that we have two options.

1. Chrome Webstore.
2. Electron using nativefier.

**Comment by leosuncin** [comment]
I can help with this

**Comment by RamazanM** [comment]
Can we make the app on https://typistapp.netlify.com/ url?

**Comment by vimark1** [comment]
@RamazanM yes, probably use the `.homepage` value in the package.json file. 
https://github.com/vimark1/typist/blob/master/package.json#L5

**Comment by leosuncin** [comment]
My pull request is WIP https://github.com/vimark1/typist/pull/88
