### ISSUE TITLE
As a user I want to add a username

### ISSUE THREAD

**Issue by vimark1** [vimark1/typist#51]
On the signup process or in an area, designated to the profile.
A user should be able to enter a username, this will be used later for leaderboard and etc.

**Comment by praveenscience** [comment]
@vimark1 Taking this up... 😃

**Comment by vimark1** [comment]
Awesome @praveenscience - we use Firebase auth, here's a link for working with the profile in Firebase https://firebase.google.com/docs/reference/js/firebase.User#updateProfile

**Comment by praveenscience** [comment]
@vimark1 Ah okay... I'll have a look. In case if I'm stuck and feel like giving up, will immediately let you know. Feel free to assign it to any others, in the mean time... 😃

**Comment by KatFrog** [comment]
/request 

@vimark1 I'll do this.

**Comment by praveenscience** [comment]
@vimark1  Let @KatFrog do it... 👍

**Comment by vimark1** [comment]
@KatFrog there's no one working on it. Feel free to send us a PR 😄

**Comment by KatFrog** [comment]
@vimark1  firebase supports a display name.  Is that what needs to be added?

**Comment by vimark1** [comment]
@KatFrog yes perfect.

**Comment by KatFrog** [comment]
@vimark1 I added display name to the sign up page.  I think that the display name needs to be added to the Redux store, once that is created, to make it available for changing in a profile page.

**Comment by vimark1** [comment]
Thanks @KatFrog - I added some comments to the PR

**Comment by vimark1** [comment]
Merged in #55
