### ISSUE TITLE
Travis CI is not running on new PRs

### ISSUE THREAD

**Issue by vimark1** [vimark1/typist#91]
for some reason the PRs created are not triggering a build on Travis CI

**Comment by clayreimann** [comment]
I'm not sure that Travis will run on forks, or maybe just not on forks of people who haven't signed up for Travis

**Comment by vimark1** [comment]
Ah, It's my fault. I was changing some of the settings on this a few days ago.
![image](https://user-images.githubusercontent.com/44329742/47695911-37c2f300-dc69-11e8-8747-5e56df840473.png)
It's fixed now, so new PRs will build.  Thanks @clayreimann
